// Helpers for the Admin-only "Download Excel Sheet" feature on Relocation sales.
//
// The CSV itself is generated by the backend (GET /api/sales/export, restricted
// to Admins) so the export cannot be obtained by a non-admin calling the API.
// What lives here is only the client-side bucket maths used to label the filter
// buttons.

// Lead buckets offered in the download filter, with their selected-state colour.
export const SALES_STATUS_FILTERS = [
  { key: 'Total', color: 'blue' },
  { key: 'Hot', color: 'red' },
  { key: 'Warm', color: 'amber' },
  { key: 'Cold', color: 'indigo' },
  { key: 'Closed', color: 'green' },
  { key: 'Active', color: 'teal' },
];

// "Total" means every entry; otherwise match the lead's queryStatus.
export const filterEntriesByStatus = (entries, filter) =>
  filter === 'Total'
    ? entries
    : entries.filter((e) => e.queryStatus?.toLowerCase() === filter.toLowerCase());

// Row count per bucket, for the numbers shown on the filter buttons.
export const getStatusCounts = (entries) =>
  SALES_STATUS_FILTERS.reduce((acc, { key }) => {
    acc[key] = filterEntriesByStatus(entries, key).length;
    return acc;
  }, {});
